version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Models/ErrorViewModel.cs
using System;

namespace RESTAPI_Client_.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/ViewModels/DataSeedVM.cs
namespace RESTAPI_Client_.ViewModels
{
    public class DataSeedVM
    {
        public bool IsError { get; set; }
        public string Description { get; set; }
    }
}

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Controllers/DataController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Net.Http;
using System.Collections.Generic;
using Newtonsoft.Json;
using RESTAPI_Client_.Models;
using Microsoft.Extensions.Configuration;
using RESTAPI_Client_.ViewModels;
using RESTAPI.Entity.Models;
using RESTAPI.DataAccess.Abstract;

namespace RESTAPI_Client_.Controllers
{
    public class DataController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IConfiguration _configuration;
        public DataController(IPostRepository postRepository, IConfiguration configuration)
        {
            _postRepository = postRepository;
            _configuration = configuration;
        }

        // Index | GET
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // Post All Data Count
            var postsCount = await _postRepository.GetCount();

            DataSeedVM dataSeedVM = new DataSeedVM();

            // Check Table Empty
            if (postsCount == 0)
            {
                List<Post> posts = new List<Post>();
                // Connect Api 
                using (var httpClient = new HttpClient())
                {
                    string api = _configuration.GetSection("Apis")["Post"];
                    using var response = await httpClient.GetAsync(api);
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    posts = JsonConvert.DeserializeObject<List<Post>>(apiResponse);
                }


                // Data Check
                if (posts.Count > 0)
                {
                    foreach (var item in posts)
                    {
                        item.Id = 0;
                    }

                    var resault = await _postRepository.CreateByAddRange(posts);
                    if(resault)
                    {
                        dataSeedVM.IsError = false;
                        dataSeedVM.Description = "Success. Data Database Saved";
                    }
                    else
                    {
                        dataSeedVM.IsError = true;
                        dataSeedVM.Description = "Database Error";
                    }
                   
                    
                }
                else
                {
                    dataSeedVM.IsError = true;
                    dataSeedVM.Description = "Api Not Connected";
                }
            }
            else
            {
                dataSeedVM.IsError = true;
                dataSeedVM.Description = "Already Data Add";
            }
           
            return View(dataSeedVM);
        }
    }
}

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RESTAPI.DataAccess.Abstract;
using RESTAPI.Entity.Models;
using RESTAPI_Client_.Extensions;
using RESTAPI_Client_.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RESTAPI_Client_.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostRepository _postRepository;

        public HomeController(IPostRepository postRepository)
        {
            _postRepository = postRepository;
        }
        // Index | GET
        public async Task<IActionResult> Index(int? index,string search)
        {

            IQueryable<Post> postQuery;
            // Check search value
            if (string.IsNullOrEmpty(search))
            {
                postQuery = _postRepository.GetAllQuery() ;
            }
            else
            {
                // Search Candition
                postQuery = _postRepository.GetAllQuery().Where(post => post.Title.Contains(search)).AsQueryable();
            }
                    
            // My Extension
            var data = await PaginationList<Post>.CreateAsync(postQuery, index ?? 1, 10, "/Home/Index?index=page&search="+search);
            return View(data);
        }
        // UseJavaScript | GET
        public async Task<IActionResult> UseJavaScript()
        {
            // Select all data send Front
            var data = await _postRepository.GetAll();
            return View(data);
        }

        



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Views/Data/Index.cshtml
@model DataSeedVM
<div class="container my-2">
    @if (Model.IsError)
    {
        <div class="alert alert-danger" role="alert">
            <h3 class="text-center">@Model.Description</h3>
        </div>
    }
    else
    {
        <div class="alert alert-success" role="alert">
            <h3 class="text-center">@Model.Description</h3>  
        </div>
    }

</div>

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Views/Home/Index.cshtml
@model PaginationList<Post>


<div class="container my-3">
        <div class="card">
            <div class="card-body">

                <h4 class="header-title">Use Back End</h4>

                <form class="d-flex justify-content-end" method="get" action="/Home/Index">
                    <div class="mb-3  d-flex">
                      <input type="text" name="search" class="form-control w-75 " placeholder="Search">
                      <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </form>

                <div class="data-tables">
                    <table id="dataTable" class="text-center table table-bordered ">
                        <thead class="bg-light thead-dark text-capitalize">
                            <tr>
                                <th>Title</th>
                                <th>Body</th>
                                <th>Id</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                                    <tr>
                                        <td>@item.Title</td>
                                        <td>@item.Body</td>
                                        <td>@item.Id</td>
                                    </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>


            <div class="card-footer d-flex justify-content-between">
                <div>
                    Showing @Model.Count to @Model.TotalElement Elements
                </div>
                <div>
                     <nav aria-label="Page navigation example">
                          <ul class="pagination">
                            @if (Model.TotalElement != 0)
                            {

                                        <li class="page-item @(Model.PaginationLinkModel.HasPreviousPage?"":"disabled")">
                                          <a class="page-link" href="@Model.PaginationLinkModel.Link.Replace("page",(Model.PageIndex - 1).ToString())" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only"></span>
                                          </a>
                                        </li>
                                        
                                        @for (int i = 1; i <= Model.TotalPages; i++)
                                        {
                                                        <li class="page-item @(Model.PageIndex == i?"active":"")">
                                                            <a class="page-link"  href="@Model.PaginationLinkModel.Link.Replace("page",i.ToString())">
                                                                @i
                                                            </a>
                                                        </li>
                                        }

                                        <li class="page-item @(Model.PaginationLinkModel.HasNextPage?"":"disabled" )">
                                          <a class="page-link" href="#" aria-label="Next" href="@Model.PaginationLinkModel.Link.Replace("page",(Model.PageIndex + 1).ToString())">
                                        <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only"></span>
                                          </a>
                                        </li>

                            }

                            </ul>
                    </nav>
                </div>

               

            </div>
        </div>
</div>

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Views/Home/UseJavaScript.cshtml
@model IList<Post>
@section header{
                <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

}

            <div class="container my-3">
                 <div class="card">
                    <div class="card-body">
                        <h4 class="header-title">Use JavaScript</h4>
                        <div class="data-tables">
                            <table id="dataTable" class="text-center">
                                <thead class="bg-light text-capitalize">
                                    <tr>
                                        <th>Title</th>
                                        <th>Body</th>
                                        <th>Id</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Title</td>
                                            <td>@item.Body</td>
                                            <td>@item.Id</td>
                                        </tr>
                                    }
                                </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
@section scripts{
                <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
                <script>
                    $(document).ready( function () {
                         if ($('#dataTable').length) {
                                    $('#dataTable').DataTable({
                                        responsive: true
                                    });
                         }
                    } );

                </script>
                <script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
}

version_repository_pattern/RESTAPI(Client)/RESTAPI(Client)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Task Rest Api(Client)</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/Untitled.png" rel="icon">
  <link href="~/assets/img/Untitled" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="~/https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">
  @RenderSection("header",false)
  <!-- =======================================================
  * Template Name: iPortfolio - v3.7.0
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="~/assets/img/Untitled.png" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="~/index.html">Nofəl Salahov</a></h1>
        <h4 class="text-light text-center">Task Rest Api(Client)</h4>
        <div class="social-links mt-3 text-center">
          <a href="https://github.com/DrMadWill" class="google-plus"><i class="bx bxl-github"></i></a>
          <a href="https://twitter.com/NofelSalahov" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="https://www.facebook.com/drmadwill" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="https://www.instagram.com/salahov__nofel/?hl=tr" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="https://www.linkedin.com/in/drmadwill/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href="/" class="nav-link scrollto"><i class="bx bx-home"></i> <span>Home(Use Back End)</span></a></li>
          <li><a  asp-controller="Home" asp-action="UseJavaScript" class="nav-link scrollto"><i class="bx bxs-file-js"></i> <span>Use Java Script </span></a></li>
          <li><a asp-controller="Data" asp-action="Index" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Data Seed</span></a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->



  <main id="main">
            @RenderBody()
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>iPortfolio</span></strong>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
        Designed by <a href="~/https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="~/#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/purecounter/purecounter.js"></script>
  <script src="~/assets/vendor/aos/aos.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/assets/vendor/typed.js/typed.min.js"></script>
  <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>
  @RenderSection("scripts",false)

</body>

</html>